### ISSUE TITLE
screen fit problem

### ISSUE THREAD

**Issue by rockets-cn** [robinz-labs/digishow#1]
![image](https://user-images.githubusercontent.com/2182466/102324750-3a097800-3fbd-11eb-9064-37a9970dfa86.png)
It seems that can't fit the screen.

**Comment by robinz-labs** [comment]
this issue has been fixed in commit 196da15827e6e3a2897b148c22cfb472dc66ffb3

just need uncheck HiDIP in the app options dialog box.

<img width="951" alt="Screen Shot 2021-11-02 at 2 47 07 PM" src="https://user-images.githubusercontent.com/70817531/139799238-b24e71d3-49fa-49af-83c2-11b5c42ae47d.png">
